[package]
name = "smart-plant-pot"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7.7"
cortex-m-rt = "0.7.5"
embedded-hal = "1.0.0"
heapless = "0.8.0"
panic-halt = "1.0.0"
rp-pico = "0.9.0"
usb-device = "0.3.2"
usbd-serial = "0.2.2"

# Embassy crates
embassy-executor = { version = "0.7.0", features = ["arch-cortex-m", "executor-thread", "executor-interrupt"]} # Choose an executor mode
embassy-time = { version = "0.4.0" } # Configure timer tick rate
embassy-sync = { version = "0.6.2" } # For async mutexes, channels if needed
embassy-futures = { version = "0.1.1" }
embassy-rp = { version = "0.4.0", default-features = false,  features = ["unstable-pac", "rp2040", "intrinsics", "critical-section-impl"] }
embassy-usb = { version = "0.4.0" } 
embassy-embedded-hal = { version = "0.3.0" }

