
[workspace]
members = ["bsp-blink", "bsp-serial", "embassy"]
resolver = "2"

[workspace.dependencies]
cortex-m = { version = "0.7.6", features = [
    "inline-asm",
], default-features = false }

embedded-hal = "1.0.0"
panic-halt = "1.0.0"


[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
strip = true
