[toolchain]
channel = "1.85"
components = ["rustfmt", "clippy", "cargo", "rust-src", "llvm-tools"]
targets = [
    "thumbv7em-none-eabi",
    "thumbv7m-none-eabi",
    "thumbv6m-none-eabi",
    "thumbv7em-none-eabihf",
    "thumbv8m.main-none-eabihf",
    "riscv32imac-unknown-none-elf",
]
