

[build]
target = "riscv32imac-unknown-none-elf"

[target.riscv32imac-unknown-none-elf]
runner = "probe-rs run --chip esp32c6"
rustflags = [
    "-C",
    "link-arg=-Tlinkall.x",
    "-C",
    "force-frame-pointers",
    "-C",
    "link-arg=-Tdefmt.x",
]

[env]
DEFMT_LOG = "debug"
ESP_LOG = "info"
GATEWAY_IP = "1.1.1.1"
HOST_IP = "1.1.1.1"
PASSWORD = "PASSWORD"
SSID = "SSID"
STATIC_IP = "1.1.1.1 "

[unstable]
build-std = ["alloc", "core"]
