[package]
edition = "2024"
name = "bsp-blink"
version = "0.1.0"

[dependencies]
cortex-m = { workspace = true }
cortex-m-rt = { workspace = true }
embedded-hal.workspace = true
panic-halt.workspace = true
rp-pico.workspace = true
