[alias]

# Build arm or riscv
build-arm = "build --target=thumbv8m.main-none-eabihf"
build-riscv = "build --target=riscv32imac-unknown-none-elf"

# Run arm or riscv
run-arm = "run --target=thumbv8m.main-none-eabihf"
run-riscv = "run --target=riscv32imac-unknown-none-elf"


[build]
# Default build target
target = "thumbv8m.main-none-eabihf"


[target.'cfg(target_os = "none")']


runner = "picotool load -u -v -x -t elf"
# Change picotool to `cargo embed` once you have setup a hardware debug probe.
# runner = "cargo embed"

[target.thumbv8m.main-none-eabihf]
rustflags = [
    "-C",
    "link-arg=--nmagic",
    "-C",
    "link-arg=-Tlink.x",
    "-C",
    "link-arg=-Tdefmt.x",
    "-C",
    "target-cpu=cortex-m33",
]


# For this target you cannot use `cortex` features of embassy.
[target.riscv32imac-unknown-none-elf]
rustflags = [
    "-C",
    "link-arg=--nmagic",
    "-C",
    "link-arg=-Trp235x_riscv.x",
    "-C",
    "link-arg=-Tdefmt.x",
]


[env]
DEFMT_LOG = "debug" # In case you use a hardware debugger.
PASSWORD = "?"      # WiFi password
SSID = "?"          # WiFi SSID
