[package]
name = "bsp-serial"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m-rt = { version = "0.7.0", default-features = false, features = [
    "device",
] }
heapless = "0.8.0"
panic-halt.workspace = true
rp-pico = "0.9.0"
usb-device = "0.3.2"
usbd-serial = "0.2.2"
